export enum SocketEvent {
   UpdateFriendInvitations = 'updateFriendInvitations',
   UpdateFriends = 'updateFriends',
   UpdateOnlineUsers = 'updateOnlineUsers',
   GetDirectChatHistory = 'getDirectChatHistory',
   SendNewDirectMessage = 'sendNewDirectMessage',
   UpdateDirectChatHistory = 'updateDirectChatHistory',
   UserTyping = 'userTypingMessage',
   LeaveRoom = 'leaveRoom',
   CreateRoom = 'createRoom',
   UpdateActiveRooms = 'updateActiveRooms',
   JoinRoom = 'joinRoom',
   RTCSignal = 'RTCSignal',
   PrepareRTC = 'prepareRTC',
   InitRTC = 'initRTC',
   RTCInitResponse = 'RTCInitResponse',
   RTCSignalFulfilled = 'RTCSignalFulfilled',
   NotifyFriendRoomCreated = 'notifyFriendRoomCreated',
}
